os:
  - linux
language: node_js
node_js:
  - "stable"
cache: yarn
script:
  - yarn flow
  - yarn lint
  - yarn test
  - yarn build
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: build
    skip-cleanup: true
    verbose: true
    on:
      branch: master
